### ISSUE TITLE
AttributeError: Data could not obtained for 'AED' from the European Central Bank database currently cached.

### ISSUE THREAD

**Issue by hvgazula** [TariqAHassan/EasyMoney#10]
```
ep.currency_converter(amount=100, from_currency="ARE", to_currency="Germany", pretty_print=True)
```

**Comment by TariqAHassan** [comment]
Hello @hvgazula 

The error message is telling you that the source used to perform the currency conversion, the European Central Bank, does not provide exchange rate information for ARE.

You can check the available data as follows:

```python
ep.options()
```

**Comment by hvgazula** [comment]
Thanks for the response. So, is there anyway to address that error using a different database?

**Comment by TariqAHassan** [comment]
The European Central Bank provides its data for free, which is why EasyMoney can use it. There are more exhaustive solutions, however they are typically come at a price. If you are willing to pay, you may want to look into the XE API ([here](https://www.xe.com/currencyconverter/)). I believe they have a free trial period too.

**Comment by hvgazula** [comment]
Okay. Thank you very much. Really appreciate your quick replies.
